import Container from "@/components/container";

import Image from "next/image";
import PageTitle from "../../_components/page-title";

import banner_img from "@/public/pages/policy/privacy_banner.webp";
import Link from "next/link";

const PrivacyPolicyPage = () => {
  return (
    <div>
      <section className="pb-10">
        <Image
          src={banner_img}
          alt="Privacy Policy of SimpliTaught"
          priority
          className="h-64 object-cover md:object-contain md:h-auto"
        />
        <div className="space-y-8 max-w-5xl mx-auto px-4 lg:px-5 pt-14">
          <PageTitle title="Privacy Policy" />
        </div>
      </section>

      <section className="pb-14">
        <Container>
          <div
            className={`
            [&>h2]:text-xl [&>h2]:md:text-2xl [&>h2]:font-semibold  [&>h2]:pb-2 [&>h2]:pt-4
            [&>p]:text-sm [&>p]:md:text-base [&>p]:font-medium [&>p]:text-slate-600
          `}
          >
            <br />
            <p className="text-sm lg:text-base text-slate-700 font-medium">
              Effective date: Sep 6, 2021
            </p>
            <br />
            <p>
              SimpliTaught LLC / SimpliTaught Group Inc. (&quot;us&quot;,
              &quot;we&quot;, or &quot;our&quot;) operates the{" "}
              <Link
                href={`https://www.simplitaught.com`}
                className="text-sm lg:text-base text-[var(--brand-color)] font-medium"
              >
                simplitaught.com{" "}
              </Link>
              website (hereinafter referred to as the Service).
            </p>
            <br />
            <p>
              This page informs you of our policies regarding the collection,
              use and disclosure of personal data when you use our Service and
              the choices you have associated with that data.
            </p>
            <br />
            <p>
              We use your data to provide and improve the Service. By using the
              Service, you agree to the collection and use of information in
              accordance with this policy. Unless otherwise defined in this
              Privacy Policy, the terms used in this Privacy Policy have the
              same meanings as in our Terms and Conditions, accessible from{" "}
              <Link
                href={`https://www.simplitaught.com`}
                className="text-sm lg:text-base text-[var(--brand-color)] font-medium"
              >
                simplitaught.com{" "}
              </Link>
              . It does not cover third party Web sites or applications to which
              we provide links from our Service.
            </p>
            <br />
            <h2>Definitions</h2>
            <div style={{ paddingLeft: 50 }} className="space-y-4">
              <div className="mt-3">
                <h6 className="text-base md:text-xl font-semibold tracking-tight">
                  Service
                </h6>
                <p>
                  Service is the{" "}
                  <Link
                    href={`https://www.simplitaught.com`}
                    className="text-sm lg:text-base text-[var(--brand-color)] font-medium"
                  >
                    simplitaught.com
                  </Link>{" "}
                  website operated by SimpliTaught LLC / SimpliTaught Group Inc.
                </p>
              </div>
              <div>
                <h6 className="text-base md:text-xl font-semibold tracking-tight">
                  Personal Data
                </h6>
                <p>
                  Personal Data means data about a living individual who can be
                  identified from those data (or from those and other
                  information either in our possession or likely to come into
                  our possession).
                </p>
              </div>
              <div>
                <h6 className="text-base md:text-xl font-semibold tracking-tight">
                  Usage Data
                </h6>
                <p>
                  Usage Data is data collected automatically either generated by
                  the use of the Service or from the Service infrastructure
                  itself (for example, the duration of a page visit).
                </p>
              </div>
              <div>
                <h6 className="text-base md:text-xl font-semibold tracking-tight">
                  Cookies
                </h6>
                <p>
                  Cookies are small files stored on your device (computer or
                  mobile device).
                </p>
              </div>
            </div>
            <br />
            <h2>Information Collection and Use</h2>
            <p>
              We collect several different types of information for various
              purposes to provide and improve our Service to you.
            </p>
            <br />
            <h6 className="text-base md:text-xl font-semibold tracking-tight">
              Types of Data Collected
            </h6>
            <br />
            <h4
              style={{ fontStyle: "italic" }}
              className="text-base md:text-xl font-semibold tracking-tight"
            >
              Personal Data
            </h4>
            <p>
              While using our Service, we may ask you to provide us with certain
              personally identifiable information that can be used to contact or
              identify you (&quot;Personal Data&quot;). Personally identifiable
              information may include, but is not limited to:
            </p>
            <br />
            <ul className="list-disc ml-10">
              <li>
                <p>Email address</p>
              </li>
              <li>
                <p>First name and last name</p>
              </li>
              <li>
                <p>Phone number</p>
              </li>
              <li>
                <p>Cookies and Usage Data</p>
              </li>
            </ul>
            <br />

            <p>
              We may use your Personal Data to contact you with newsletters,
              marketing or promotional materials and other information that may
              be of interest to you. You may opt out of receiving any, or all,
              of these communications from us by following the unsubscribe link
              or the instructions provided in any email we send.
            </p>
            <br />

            <h4
              style={{ fontStyle: "italic" }}
              className="text-base md:text-xl font-semibold tracking-tight mb-2"
            >
              Usage Data
            </h4>

            <p>
              We may also collect information on how the Service is accessed and
              used (&quot;Usage Data&quot;). This Usage Data may include
              information such as your computer&#39;s Internet Protocol address
              (e.g. IP address), browser type, browser version, the pages of our
              Service that you visit, the time and date of your visit, the time
              spent on those pages, unique device identifiers and other
              diagnostic data.
            </p>
            <br />

            <h4
              style={{ fontStyle: "italic" }}
              className="text-base md:text-xl font-semibold tracking-tight mb-2"
            >
              Tracking Cookies Data
            </h4>

            <p>
              We use cookies and similar tracking technologies to track the
              activity on our Service and we hold certain information.
            </p>
            <br />
            <p>
              Cookies are files with a small amount of data which may include an
              anonymous unique identifier. Cookies are sent to your browser from
              a website and stored on your device. Other tracking technologies
              are also used such as beacons, tags and scripts to collect and
              track information and to improve and analyse our Service.
            </p>
            <br />
            <p>
              You can instruct your browser to refuse all cookies or to indicate
              when a cookie is being sent. However, if you do not accept
              cookies, you may not be able to use some portions of our Service.
            </p>
            <br />
            <p className="text-base md:text-xl font-semibold tracking-tight mb-2">
              Examples of Cookies we use:
            </p>

            <ul className="list-disc ml-10">
              <li>
                <p>
                  <strong>Session Cookies.</strong> We use Session Cookies to
                  operate our Service.
                </p>
              </li>
              <li>
                <p>
                  <strong>Preference Cookies.</strong> We use Preference Cookies
                  to remember your preferences and various settings.
                </p>
              </li>
              <li>
                <p>
                  <strong>Security Cookies.</strong> We use Security Cookies for
                  security purposes.
                </p>
              </li>
            </ul>
            <br />
            <h2>Use of Data</h2>
            <p>
              SimpliTaught LLC / SimpliTaught Group Inc. uses the collected data
              for various purposes:
            </p>
            <br />
            <ul className="list-disc ml-10">
              <li>
                <p>To provide and maintain our Service</p>
              </li>
              <li>
                <p>To notify you about changes to our Service</p>
              </li>
              <li>
                <p>
                  To allow you to participate in interactive features of our
                  Service when you choose to do so
                </p>
              </li>
              <li>
                <p>To provide customer support</p>
              </li>
              <li>
                <p>
                  To gather analysis or valuable information so that we can
                  improve our Service
                </p>
              </li>
              <li>
                <p>To monitor the usage of our Service</p>
              </li>
              <li>
                <p>To detect, prevent and address technical issues</p>
              </li>
              <li>
                <p>
                  To provide you with news, special offers and general
                  information about other goods, services and events which we
                  offer that are similar to those that you have already
                  purchased or enquired about unless you have opted not to
                  receive such information
                </p>
              </li>
            </ul>
            <br />

            <h2 className="text-base md:text-xl tracking-tight font-semibold">
              Transfer of Data
            </h2>
            <p>
              Your information, including Personal Data, may be transferred to -
              and maintained on - computers located outside of your state,
              province, country or other governmental jurisdiction where the
              data protection laws may differ from those of your jurisdiction.
              <br />
              <br />
              If you are located outside United States and choose to provide
              information to us, please note that we transfer the data,
              including Personal Data, to United States and process it there.
              <br />
              <br />
              Your consent to this Privacy Policy followed by your submission of
              such information represents your agreement to that transfer.
              <br />
              <br />
              SimpliTaught LLC / SimpliTaught Group Inc. will take all the steps
              reasonably necessary to ensure that your data is treated securely
              and in accordance with this Privacy Policy and no transfer of your
              Personal Data will take place to an organisation or a country
              unless there are adequate controls in place including the security
              of your data and other personal information.
            </p>
            <br />
            <h2>Disclosure of Data</h2>
            <br />
            <h5 className="text-base md:text-xl tracking-tight font-semibold">
              Business Transaction
            </h5>
            <p>
              If SimpliTaught LLC / SimpliTaught Group Inc. is involved in a
              merger, acquisition or asset sale, your Personal Data may be
              transferred. We will provide notice before your Personal Data is
              transferred and becomes subject to a different Privacy Policy.
            </p>
            <br />
            <h5 className="text-base md:text-xl tracking-tight font-semibold">
              Disclosure for Law Enforcement
            </h5>
            <p>
              Under certain circumstances, SimpliTaught LLC / SimpliTaught Group
              Inc. may be required to disclose your Personal Data if required to
              do so by law or in response to valid requests by public
              authorities (e.g. a court or a government agency).
            </p>
            <br />
            <h5 className="text-base md:text-xl tracking-tight font-semibold">
              Legal Requirements
            </h5>
            <p>
              SimpliTaught LLC / SimpliTaught Group Inc. may disclose your
              Personal Data in the good faith belief that such action is
              necessary to:
            </p>
            <ul className="list-disc ml-10">
              <li>
                <p>To comply with a legal obligation</p>
              </li>
              <li>
                <p>
                  To protect and defend the rights or property of SimpliTaught
                  LLC / SimpliTaught Group Inc.
                </p>
              </li>
              <li>
                <p>
                  To prevent or investigate possible wrongdoing in connection
                  with the Service
                </p>
              </li>
              <li>
                <p>
                  To protect the personal safety of users of the Service or the
                  public
                </p>
              </li>
              <li>
                <p>To protect against legal liability</p>
              </li>
            </ul>
            <br />
            <h5 className="text-base md:text-xl tracking-tight font-semibold">
              Security of Data
            </h5>
            <p>
              The security of your data is important to us but remember that no
              method of transmission over the Internet or method of electronic
              storage is 100% secure. While we strive to use commercially
              acceptable means to protect your Personal Data, we cannot
              guarantee its absolute security.
            </p>
            <br />
            <h5 className="text-base md:text-xl tracking-tight font-semibold">
              Our Policy on &quot;Do Not Track&quot; Signals under the
              California Online Protection Act (CalOPPA)
            </h5>
            <p>
              We do not support Do Not Track (&quot;DNT&quot;). Do Not Track is
              a preference you can set in your web browser to inform websites
              that you do not want to be tracked.
              <br />
              You can enable or disable Do Not Track by visiting the Preferences
              or Settings page of your web browser.
            </p>
            <br />
            <h4 className="text-base md:text-xl tracking-tight font-semibold">
              Service Providers
            </h4>
            <p>
              We may employ third party companies and individuals to facilitate
              our Service (&quot;Service Providers&quot;), provide the Service
              on our behalf, perform Service-related services or assist us in
              analysing how our Service is used.
              <br />
              These third parties have access to your Personal Data only to
              perform these tasks on our behalf and are obligated not to
              disclose or use it for any other purpose.
            </p>
            <br />
            <h4 className="text-base md:text-xl tracking-tight font-semibold">
              Analytics
            </h4>
            <p>
              We may use third-party Service Providers to monitor and analyse
              the use of our Service.
            </p>
            <br />
            <div style={{ paddingLeft: 50 }}>
              <p>
                <strong>Google Analytics</strong>
                <br />
                Google Analytics is a web analytics service offered by Google
                that tracks and reports website traffic. Google uses the data
                collected to track and monitor the use of our Service. This data
                is shared with other Google services. Google may use the
                collected data to contextualise and personalise the ads of its
                own advertising network. You can opt-out of having made your
                activity on the Service available to Google Analytics by
                installing the Google Analytics opt-out browser add-on. The
                add-on prevents the Google Analytics JavaScript (ga.js,
                analytics.js and dc.js) from sharing information with Google
                Analytics about visits activity. For more information on the
                privacy practices of Google, please visit the Google Privacy
                Terms web page:
                <a
                  href="https://policies.google.com/privacy?hl=en"
                  target="_blank"
                  rel="noopener noreferrer"
                  className="underline text-[var(--brand-color)] font-semibold ml-1"
                >
                  https://policies.google.com/privacy?hl=en
                </a>
              </p>
            </div>
            <br />
            <h4 className="text-base md:text-xl tracking-tight font-semibold">
              Links to Other Sites
            </h4>
            <p>
              Our Service may contain links to other sites that are not operated
              by us. If you click a third party link, you will be directed to
              that third party&#39;s site. We strongly advise you to review the
              Privacy Policy of every site you visit.
              <br />
              <br />
              We have no control over and assume no responsibility for the
              content, privacy policies or practices of any third party sites or
              services.
            </p>
            <br />
            <h4 className="text-base md:text-xl tracking-tight font-semibold">
              Children&#39;s Privacy
            </h4>
            <p>
              Our Service does not address anyone under the age of 18
              (&quot;Children&quot;).
              <br />
              <br />
              We do not knowingly collect personally identifiable information
              from anyone under the age of 18. If you are a parent or guardian
              and you are aware that your Child has provided us with Personal
              Data, please contact us. If we become aware that we have collected
              Personal Data from children without verification of parental
              consent, we take steps to remove that information from our
              servers.
            </p>
            <br />
            <h4 className="text-base md:text-xl tracking-tight font-semibold">
              Changes to This Privacy Policy
            </h4>
            <p>
              We may update our Privacy Policy from time to time. We will notify
              you of any changes by posting the new Privacy Policy on this page.
              <br />
              We will let you know via email and/or a prominent notice on our
              Service, prior to the change becoming effective and update the
              &quot;effective date&quot; at the top of this Privacy Policy.
              <br />
              You are advised to review this Privacy Policy periodically for any
              changes. Changes to this Privacy Policy are effective when they
              are posted on this page.
            </p>
            <br />
            <h5 className="text-base md:text-xl tracking-tight font-semibold">
              Contact Us
            </h5>
            <p>
              If you have any questions about this Privacy Policy, please{" "}
              <Link
                href="/contact-us"
                className="font-semibold text-[var(--brand-color)]"
              >
                contact us:{" "}
              </Link>
            </p>
            <ul className="list-disc ml-10">
              <li>
                <p>
                  {" "}
                  By email: <strong>support@simplitaught.com</strong>
                </p>
              </li>
            </ul>
          </div>
        </Container>
      </section>
    </div>
  );
};

export default PrivacyPolicyPage;
